

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peliculasdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  peliculas-api:
    build: .
    container_name: peliculas-api
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
